name: "feishu info"
on:
  schedule:
    - cron: "*/30 * * * *" # 每30分钟运行一次
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: 安装必要插件
        run: pip install feedparser requests
      - name: 开始抓取并推送
        run: python main.py
        env:
          RSS_URL: ${{ secrets.RSS_URL }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
